### ISSUE TITLE
regarding to wifi connection on desktop

### ISSUE THREAD

**Issue by kenloumixx** [Road-Balance/rb_unitree_legged_sdk#1]
Hello.
First of all, thank you for providing the code with Python.
I have a question, I am using a desktop, did you connect to robot Wi-Fi? Or did you plug in the LAN?
I'd like to ask you if you connected to Wi-Fi right away with your desktop.
Thank you.

**Comment by kimsooyoung** [comment]
Thank you for your interest.

First of all in order to control real-robot, There's basically three ways.

1. Build your app in robot's jetson directly. 
If your robot is Unitree-A1 (is it right?) You'll find there's jetson NX in that. 
So, Connect HDMI to there and clone this sdk, And after you build that you can run your problem directly in robot's jetson.
But, It's... dangerous. Be careful from his kicking. 

2. Connection though LAN
On the back of robot, there'll be one LAN port for Ethernet Communication.
You can use it by connecting that with your desktop. But you must set static IP for using that (usually 192.168.123)
In my case, I usually do work in my PC first, and check all errors at there, And finally copy all codes into robot's jetson.
But jetson has differnet architecture so you need to build that again.

3. Remote Connection.
In my case, I'm using ROS now. So I can transmit data through ROS protocol. 
ROS makes it ease to communicate btw multiple devices, If they were sharing same AP.
So, If you familliar with ROS. Try to do that first. But You'll need extra software which named unitree_ros_real. 

Lastly, What do you want to implement? If you don't mind, Tell me about your plan plz.

**Comment by kenloumixx** [comment]
Thank you for your answer. 
We are now trying to access the subnet in the robot wifi of A1 and do ssh communication. 
I want to ask you how you got the initial network because I can get robot Wi-Fi on my laptop (Mac M1) and even on my phone, but my desktop can't get Wi-Fi (Ubuntu 20.04).

**Comment by kimsooyoung** [comment]
First of all, Sorry for late

Basically the "wifi" you mean has some kinds of different meaning from that for ssh or sort of stuffs.

Robot's wifi, such like A1-xxxx is just for Unitree Mobile Application and not for ssh.

Be begin with, in order to use ssh connection, you need to use extra wifi apator for your jetson. 

And connect your Jetson to your favor wifi (By HDMI connected Monitor in my case.)
After then, turn on terminal program in Jetson and then type `ifconfig` for ip number. (such like 192.168.0.xx)

Finally, On your Laptop, type ssh unitree@192.168.0.XXX for ssh connection then type unitree's Jetson's password (usually 123)

So... That's all about that!! Hope to achive success and Let me know if there's any other questions

**Comment by kenloumixx** [comment]
Thank you for the response :)

May I ask another question?

Now I am stuck in the error describing 'pthread set sched policy failed'. 

However beside this, I'd like to ask whether the communication can work only if the desktop PC that is supposed to control the A1 hardware and the A1 hardware are on the same subnet. 

That is, after I get the ip adress from jetson, should I maintain the wifi connection for the remote control via desktop terminal?  Or can I just break the wifi connection and publish the ros topics as running A1 hardware's roscore?

Thanks for answering these questions.. :P

**Comment by kimsooyoung** [comment]
Your question is little... confusing to me. Btw, I think that you're not familliar  with ROS communication system.

First of all, All machines shoud be connectied under the same subnet => That's right. And that's why I mentioned ip number 192.168.XX,XX. 

Second, Yes of course, you must preserve your wifi connection for remote controlling. 

Lastly, where you bought A1? I think you can get answer for those questions from Vender you ordered A1. If you don't mind. Please let me know where you purchased it from.

**Comment by kenloumixx** [comment]
Thank you for the explanations that you gave :-) 
And also sorry for the insufficient information.
I didn't bought it directly, so there's no way of talking to the vender.. 

By the way, I totally understood what you said, and I connected wifi adaptor to jetson. 
Under the same subnet (the wifi of the room), I launched the base.launch from remote PC to A1 jetson following the manual and it says
`RLException: ERROR: unable to contact ROS master at [http://192.168.123.12:11311]`

Can I ask if you added the below two lines to bashrc file of both user and root? 
And If you did, how did you make it function? 
 `export ROS_HOSTNAME=<Remote PC IP>`
 `export ROS_MASTER_URI=http://192.168.123.12:11311`

Thanks in advance for the answers.. you are literally saving me..

**Comment by kenloumixx** [comment]
Thank you for the explanation that you gave :-)
Actually, I got this A1 not directly from the vendor, therefore for me there's no way of talking to the vendor.
And I feel really sorry for asking this basic information :-(
 
If it doesn't bother you, may I ask another question?
I followed your instruction and now the connection is built as I double-checked with ping test and ros graph. 
However, when I send a message, the A1 doesn't move, and it is just still.

I send this kind of message and would you mind if I ask the command is right?
The command is 
`rostopic pub -r 1 unitree/cmd_vel geometry_msgs/Twist -- '{linear: {x: 1, y: 0, z: 0}, angular: {x: 0, y: 0, z: 0}}'`
Thanks for your generosity in advance!

**Comment by kimsooyoung** [comment]
Command for /cmd_vel seems okay it works for me.

"A1 doesn't move" Well... There's so many things to consider so I cannot diagnose your symptom accurately.

What about ask for any vendors in your country? Most of them has technical CS.
In my place, South Korea, There're more than 2 companies providing Technical Service.

Your problem requires meticulous inspection (Both for Hardware and Software).
Sorry for disappointing answer and hope to successfully implement your project.
